---
 - name: Create a user and clone a remote git repo to all the users home dir
   hosts: all
   tasks:
     - name: Create user
       user:
         name: Shankar
         password: intelliqit
         home: /tmp/shankar
         uid: 8989
         comment: "a super user"
         shell: /bin/bash
     - name: Clone a repository from github
       git:
         repo: https://github.com/intelliqittrainings/maven.git
         dest: /tmp/shankar/mygit
     - name: file Permissions RWX
       file:
         path: /tmp/shankar
         owner: root
         group: shankar
         mode: 750
         recurse: yes
...
