---
- name: Copy customized tomcat-users.xml file
  copy:
    src: "{{file1}}"
    dest: "{{dest1}}"
- name: Changine port 8080 to 9090
  replace:
    regexp: "{{port1}}"
    replace: "{{port2}}"
    path: "{{path1}}"
  notify: check url response
...
